
services:
    nginx-marinerapp:
      container_name: nginx-marinerapp
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./docker/nginx-config/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - marinerapp-network

    db-marinerapp:
      container_name: db-marinerapp
      image: postgis/postgis:14-3.2
      volumes:
        - ../../mariner_app-postgres-data:/var/lib/postgresql/data
        - ../../mariner_app-postgres-log:/var/log/postgresql
        - ./docker/init-unix.sql:/docker-entrypoint-initdb.d/init.sql # to set up the DB template
      ports:
        - '5433:5432'
      env_file: 
        - ./docker/env_file.env
      networks:
        - marinerapp-network

    elastic-bindmount-init-marinerapp:
      image: alpine
      container_name: elastic-bindmount-init-marinerapp
      restart: "no"
      entrypoint: |
        /bin/sh -c "chown 1000:1000 /esBindMount"
      volumes:
        - ../../mariner_app-elasticsearch-data:/esBindMount


    elasticsearch-marinerapp:
      container_name: elasticsearch-marinerapp
      image: elasticsearch:8.5.0
      volumes:
        #- ../../elasticsearch_data_mariner_app:/usr/share/elasticsearch/data
        - ../../mariner_app-elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9201:9200"
        - "9301:9300"
      env_file: 
        - ./docker/env_file.env
      networks:
        - marinerapp-network
      depends_on:
        - elastic-bindmount-init-marinerapp

    rabbitmq-marinerapp:
      container_name: rabbitmq-marinerapp
      image: rabbitmq:3.8-management
      hostname: my-rabbit
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - rabbitmq-logs:/var/log/rabbitmq/log
      ports:
        - 5673:5672
        - 15673:15672
      networks:
        - marinerapp-network

    #pg-feat-marinerapp:
    #  container_name: pg-feat-marinerapp
    #  image: pramsey/pg_featureserv
    #  volumes:
    #    - ../../pg_featureserv_config_mariner_app:/config
    #  environment:
    #    - DATABASE_URL=postgresql://arches_spatial_views:arches_spatial_views@db-marinerapp:5432/mariner_app
    #  ports:
    #    - 9000:9000
    #  networks:
    #    - marinerapp-network
    #  depends_on:
    #    - db-marinerapp
    
    #pg-tile-marinerapp:
    #  container_name: pg-tile-marinerapp
    #  image: pramsey/pg_tileserv
    #  volumes:
    #    - ../../pg_tileserv_config_mariner_app:/config
    #  environment:
    #    - DATABASE_URL=postgresql://arches_spatial_views:arches_spatial_views@db-marinerapp:5432/mariner_app
    #  ports:
    #    - 7800:7800
    #  networks:
    #    - marinerapp-network
    #  depends_on:
    #    - db-marinerapp


networks:
  marinerapp-network:
    name: marinerapp-network
    driver: bridge

volumes:
    rabbitmq-logs:
    rabbitmq-data: